#!/bin/sh

echo "# This file was generated by bootstrap.sh" > MakefileTest.am
awk '
/^TEST: .*\.c\>/ {
	src = $2
	exe = $2
	derived = $2
	sources = $0
	gsub("TEST: *"src" *", "", sources)
	if (length(sources))
		sources = sources " tap.c"
	else
		sources = sources "tap.c"

	gsub("\\.c$", ".t", exe)
	gsub("[-.]", "_", derived)
	gsub("_c$", "_t", derived)

	print "TESTS += " exe\
	"\ncheck_PROGRAMS += " exe\
	"\n"derived"_SOURCES = " src" "sources\
	"\n"derived"_DEPENDENCIES = $(top_builddir)/src/libferite.la\n"
	next
}
{ print }' MakefileTest.am.stub >> MakefileTest.am
