/* This file has been automatically generated by builder part of the ferite distribution */
#ifndef __example_module_HEADER__
#define __example_module_HEADER__

    /* Start user defined header code */
 

#include <stdio.h> /* for printf */


    /* End user defined header code */
FE_NATIVE_FUNCTION( example_module_foo_bar );
FE_NATIVE_FUNCTION( example_module_foo_stix );

#endif /* __example_module_HEADER__ */
