/* This file has been automatically generated by builder part of the ferite distribution */
#include <ferite.h>       /* we need this without a doubt */
#include "example_module_header.h"  /* this is the module header */

void example_module_init( FeriteScript *script )
{

      ferite_module_register_native_function( script, "foo.bar", example_module_foo_bar );
      ferite_module_register_native_function( script, "foo.stix", example_module_foo_stix );
}

void example_module_deinit()
{
}

