/* This file has been automatically generated by builder part of the ferite distribution */
/* file: example_module_foo.c */
/* namespace: foo */

#include <ferite.h>       /* we need this without a doubt */
#include "example_module_header.h"  /* this is the module header */

FE_NATIVE_FUNCTION( example_module_foo_bar )
{
   char *data = fcalloc( strlen(VAS(params[0]))+1, sizeof(char) );

   ferite_get_parameters( params, 1, data );

   { /* Main function body. */
#line 36 "ExampleModule.fec"
{}
   }
   FE_RETURN_VOID;
}

FE_NATIVE_FUNCTION( example_module_foo_stix )
{
   double amount;

   ferite_get_parameters( params, 1, &amount );

   { /* Main function body. */
#line 38 "ExampleModule.fec"

   
	  printf( "stix: %d\n", (long)amount );
   
   }
   FE_RETURN_VOID;
}

