/* This file was autogenerated by consts.sh from consts.txt */
long constant_values[] = {
#ifdef O_RDONLY
O_RDONLY,
#endif
#ifdef O_WRONLY
O_WRONLY,
#endif
#ifdef O_RDWR
O_RDWR,
#endif
#ifdef O_CREAT
O_CREAT,
#endif
#ifdef O_EXCL
O_EXCL,
#endif
#ifdef O_TRUNC
O_TRUNC,
#endif
#ifdef O_APPEND
O_APPEND,
#endif
0 };
char *constant_names[] = {
#ifdef O_RDONLY
"O_RDONLY",
#endif
#ifdef O_WRONLY
"O_WRONLY",
#endif
#ifdef O_RDWR
"O_RDWR",
#endif
#ifdef O_CREAT
"O_CREAT",
#endif
#ifdef O_EXCL
"O_EXCL",
#endif
#ifdef O_TRUNC
"O_TRUNC",
#endif
#ifdef O_APPEND
"O_APPEND",
#endif
"" };
