/* This file was autogenerated by consts.sh from consts.txt */
long constant_values[] = {
#ifdef LOG_PID
LOG_PID,
#endif
#ifdef LOG_CONS
LOG_CONS,
#endif
#ifdef LOG_NDELAY
LOG_NDELAY,
#endif
#ifdef LOG_PERROR
LOG_PERROR,
#endif
#ifdef LOG_KERN
LOG_KERN,
#endif
#ifdef LOG_USER
LOG_USER,
#endif
#ifdef LOG_MAIL
LOG_MAIL,
#endif
#ifdef LOG_DAEMON
LOG_DAEMON,
#endif
#ifdef LOG_SYSLOG
LOG_SYSLOG,
#endif
#ifdef LOG_LPR
LOG_LPR,
#endif
#ifdef LOG_NEWS
LOG_NEWS,
#endif
#ifdef LOG_UUCP
LOG_UUCP,
#endif
#ifdef LOG_CRON
LOG_CRON,
#endif
#ifdef LOG_AUTHPRIV
LOG_AUTHPRIV,
#endif
#ifdef LOG_FTP
LOG_FTP,
#endif
#ifdef LOG_LOCAL0
LOG_LOCAL0,
#endif
#ifdef LOG_LOCAL1
LOG_LOCAL1,
#endif
#ifdef LOG_LOCAL2
LOG_LOCAL2,
#endif
#ifdef LOG_LOCAL3
LOG_LOCAL3,
#endif
#ifdef LOG_LOCAL4
LOG_LOCAL4,
#endif
#ifdef LOG_LOCAL5
LOG_LOCAL5,
#endif
#ifdef LOG_LOCAL6
LOG_LOCAL6,
#endif
#ifdef LOG_LOCAL7
LOG_LOCAL7,
#endif
0 };
char *constant_names[] = {
#ifdef LOG_PID
"LOG_PID",
#endif
#ifdef LOG_CONS
"LOG_CONS",
#endif
#ifdef LOG_NDELAY
"LOG_NDELAY",
#endif
#ifdef LOG_PERROR
"LOG_PERROR",
#endif
#ifdef LOG_KERN
"LOG_KERN",
#endif
#ifdef LOG_USER
"LOG_USER",
#endif
#ifdef LOG_MAIL
"LOG_MAIL",
#endif
#ifdef LOG_DAEMON
"LOG_DAEMON",
#endif
#ifdef LOG_SYSLOG
"LOG_SYSLOG",
#endif
#ifdef LOG_LPR
"LOG_LPR",
#endif
#ifdef LOG_NEWS
"LOG_NEWS",
#endif
#ifdef LOG_UUCP
"LOG_UUCP",
#endif
#ifdef LOG_CRON
"LOG_CRON",
#endif
#ifdef LOG_AUTHPRIV
"LOG_AUTHPRIV",
#endif
#ifdef LOG_FTP
"LOG_FTP",
#endif
#ifdef LOG_LOCAL0
"LOG_LOCAL0",
#endif
#ifdef LOG_LOCAL1
"LOG_LOCAL1",
#endif
#ifdef LOG_LOCAL2
"LOG_LOCAL2",
#endif
#ifdef LOG_LOCAL3
"LOG_LOCAL3",
#endif
#ifdef LOG_LOCAL4
"LOG_LOCAL4",
#endif
#ifdef LOG_LOCAL5
"LOG_LOCAL5",
#endif
#ifdef LOG_LOCAL6
"LOG_LOCAL6",
#endif
#ifdef LOG_LOCAL7
"LOG_LOCAL7",
#endif
"" };
