/* This file was autogenerated by consts.sh from consts.txt */
long constant_values[] = {
#ifdef PRIO_PROCESS
PRIO_PROCESS,
#endif
#ifdef PRIO_PGRP
PRIO_PGRP,
#endif
#ifdef PRIO_USER
PRIO_USER,
#endif
#ifdef SIGHUP
SIGHUP,
#endif
#ifdef SIGINT
SIGINT,
#endif
#ifdef SIGQUIT
SIGQUIT,
#endif
#ifdef SIGILL
SIGILL,
#endif
#ifdef SIGTRAP
SIGTRAP,
#endif
#ifdef SIGABRT
SIGABRT,
#endif
#ifdef SIGBUS
SIGBUS,
#endif
#ifdef SIGFPE
SIGFPE,
#endif
#ifdef SIGKILL
SIGKILL,
#endif
#ifdef SIGUSR1
SIGUSR1,
#endif
#ifdef SIGSEGV
SIGSEGV,
#endif
#ifdef SIGUSR2
SIGUSR2,
#endif
#ifdef SIGPIPE
SIGPIPE,
#endif
#ifdef SIGALRM
SIGALRM,
#endif
#ifdef SIGTERM
SIGTERM,
#endif
#ifdef SIGCHLD
SIGCHLD,
#endif
#ifdef SIGCONT
SIGCONT,
#endif
#ifdef SIGSTOP
SIGSTOP,
#endif
#ifdef SIGTSTP
SIGTSTP,
#endif
#ifdef SIGTTIN
SIGTTIN,
#endif
#ifdef SIGTTOU
SIGTTOU,
#endif
#ifdef SIGURG
SIGURG,
#endif
#ifdef SIGXCPU
SIGXCPU,
#endif
#ifdef SIGXFSZ
SIGXFSZ,
#endif
#ifdef SIGVTALRM
SIGVTALRM,
#endif
#ifdef SIGPROF
SIGPROF,
#endif
#ifdef SIGWINCH
SIGWINCH,
#endif
#ifdef SIGIO
SIGIO,
#endif
#ifdef SIGSTKFLT
SIGSTKFLT,
#endif
#ifdef RLIMIT_CPU
RLIMIT_CPU,
#endif
#ifdef RLIMIT_DATA
RLIMIT_DATA,
#endif
#ifdef RLIMIT_FSIZE
RLIMIT_FSIZE,
#endif
#ifdef RLIMIT_MEMLOCK
RLIMIT_MEMLOCK,
#endif
#ifdef RLIMIT_NOFILE
RLIMIT_NOFILE,
#endif
#ifdef RLIMIT_NPROC
RLIMIT_NPROC,
#endif
#ifdef RLIMIT_RSS
RLIMIT_RSS,
#endif
#ifdef RLIMIT_STACK
RLIMIT_STACK,
#endif
#ifdef RLIM_INFINITY
RLIM_INFINITY,
#endif
#ifdef RLIMIT_LOCKS
RLIMIT_LOCKS,
#endif
#ifdef EPERM
EPERM,
#endif
#ifdef ENOENT
ENOENT,
#endif
#ifdef ESRCH
ESRCH,
#endif
#ifdef EINTR
EINTR,
#endif
#ifdef EIO
EIO,
#endif
#ifdef ENXIO
ENXIO,
#endif
#ifdef E2BIG
E2BIG,
#endif
#ifdef ENOEXEC
ENOEXEC,
#endif
#ifdef EBADF
EBADF,
#endif
#ifdef ECHILD
ECHILD,
#endif
#ifdef EAGAIN
EAGAIN,
#endif
#ifdef ENOMEM
ENOMEM,
#endif
#ifdef EACCES
EACCES,
#endif
#ifdef EFAULT
EFAULT,
#endif
#ifdef ENOTBLK
ENOTBLK,
#endif
#ifdef EBUSY
EBUSY,
#endif
#ifdef EEXIST
EEXIST,
#endif
#ifdef EXDEV
EXDEV,
#endif
#ifdef ENODEV
ENODEV,
#endif
#ifdef ENOTDIR
ENOTDIR,
#endif
#ifdef EISDIR
EISDIR,
#endif
#ifdef EINVAL
EINVAL,
#endif
#ifdef ENFILE
ENFILE,
#endif
#ifdef EMFILE
EMFILE,
#endif
#ifdef ENOTTY
ENOTTY,
#endif
#ifdef ETXTBSY
ETXTBSY,
#endif
#ifdef EFBIG
EFBIG,
#endif
#ifdef ENOSPC
ENOSPC,
#endif
#ifdef ESPIPE
ESPIPE,
#endif
#ifdef EROFS
EROFS,
#endif
#ifdef EMLINK
EMLINK,
#endif
#ifdef EPIPE
EPIPE,
#endif
#ifdef EDOM
EDOM,
#endif
#ifdef ERANGE
ERANGE,
#endif
#ifdef EDEADLK
EDEADLK,
#endif
#ifdef ENAMETOOLONG
ENAMETOOLONG,
#endif
#ifdef ENOLCK
ENOLCK,
#endif
#ifdef ENOSYS
ENOSYS,
#endif
#ifdef ENOTEMPTY
ENOTEMPTY,
#endif
#ifdef ELOOP
ELOOP,
#endif
#ifdef EWOULDBLOCK
EWOULDBLOCK,
#endif
#ifdef ENOMSG
ENOMSG,
#endif
#ifdef EIDRM
EIDRM,
#endif
#ifdef ECHRNG
ECHRNG,
#endif
#ifdef EL2NSYNC
EL2NSYNC,
#endif
#ifdef EL3HLT
EL3HLT,
#endif
#ifdef EL3RST
EL3RST,
#endif
#ifdef ELNRNG
ELNRNG,
#endif
#ifdef EUNATCH
EUNATCH,
#endif
#ifdef ENOCSI
ENOCSI,
#endif
#ifdef EL2HLT
EL2HLT,
#endif
#ifdef EBADE
EBADE,
#endif
#ifdef EBADR
EBADR,
#endif
#ifdef EXFULL
EXFULL,
#endif
#ifdef ENOANO
ENOANO,
#endif
#ifdef EBADRQC
EBADRQC,
#endif
#ifdef EBADSLT
EBADSLT,
#endif
#ifdef EBFONT
EBFONT,
#endif
#ifdef ENOSTR
ENOSTR,
#endif
#ifdef ENODATA
ENODATA,
#endif
#ifdef ETIME
ETIME,
#endif
#ifdef ENOSR
ENOSR,
#endif
#ifdef ENONET
ENONET,
#endif
#ifdef ENOPKG
ENOPKG,
#endif
#ifdef EREMOTE
EREMOTE,
#endif
#ifdef ENOLINK
ENOLINK,
#endif
#ifdef EADV
EADV,
#endif
#ifdef ESRMNT
ESRMNT,
#endif
#ifdef ECOMM
ECOMM,
#endif
#ifdef EPROTO
EPROTO,
#endif
#ifdef EMULTIHOP
EMULTIHOP,
#endif
#ifdef EDOTDOT
EDOTDOT,
#endif
#ifdef EBADMSG
EBADMSG,
#endif
#ifdef EOVERFLOW
EOVERFLOW,
#endif
#ifdef ENOTUNIQ
ENOTUNIQ,
#endif
#ifdef EBADFD
EBADFD,
#endif
#ifdef EREMCHG
EREMCHG,
#endif
#ifdef ELIBACC
ELIBACC,
#endif
#ifdef ELIBBAD
ELIBBAD,
#endif
#ifdef ELIBSCN
ELIBSCN,
#endif
#ifdef ELIBMAX
ELIBMAX,
#endif
#ifdef ELIBEXEC
ELIBEXEC,
#endif
#ifdef EILSEQ
EILSEQ,
#endif
#ifdef ERESTART
ERESTART,
#endif
#ifdef ESTRPIPE
ESTRPIPE,
#endif
#ifdef EUSERS
EUSERS,
#endif
#ifdef ENOTSOCK
ENOTSOCK,
#endif
#ifdef EDESTADDRREQ
EDESTADDRREQ,
#endif
#ifdef EMSGSIZE
EMSGSIZE,
#endif
#ifdef EPROTOTYPE
EPROTOTYPE,
#endif
#ifdef ENOPROTOOPT
ENOPROTOOPT,
#endif
#ifdef EPROTONOSUPPORT
EPROTONOSUPPORT,
#endif
#ifdef ESOCKTNOSUPPORT
ESOCKTNOSUPPORT,
#endif
#ifdef EOPNOTSUPP
EOPNOTSUPP,
#endif
#ifdef EPFNOSUPPORT
EPFNOSUPPORT,
#endif
#ifdef EAFNOSUPPORT
EAFNOSUPPORT,
#endif
#ifdef EADDRINUSE
EADDRINUSE,
#endif
#ifdef EADDRNOTAVAIL
EADDRNOTAVAIL,
#endif
#ifdef ENETDOWN
ENETDOWN,
#endif
#ifdef ENETUNREACH
ENETUNREACH,
#endif
#ifdef ENETRESET
ENETRESET,
#endif
#ifdef ECONNABORTED
ECONNABORTED,
#endif
#ifdef ECONNRESET
ECONNRESET,
#endif
#ifdef ENOBUFS
ENOBUFS,
#endif
#ifdef EISCONN
EISCONN,
#endif
#ifdef ENOTCONN
ENOTCONN,
#endif
#ifdef ESHUTDOWN
ESHUTDOWN,
#endif
#ifdef ETOOMANYREFS
ETOOMANYREFS,
#endif
#ifdef ETIMEDOUT
ETIMEDOUT,
#endif
#ifdef ECONNREFUSED
ECONNREFUSED,
#endif
#ifdef EHOSTDOWN
EHOSTDOWN,
#endif
#ifdef EHOSTUNREACH
EHOSTUNREACH,
#endif
#ifdef EALREADY
EALREADY,
#endif
#ifdef EINPROGRESS
EINPROGRESS,
#endif
#ifdef ESTALE
ESTALE,
#endif
#ifdef EUCLEAN
EUCLEAN,
#endif
#ifdef ENOTNAM
ENOTNAM,
#endif
#ifdef ENAVAIL
ENAVAIL,
#endif
#ifdef EISNAM
EISNAM,
#endif
#ifdef EREMOTEIO
EREMOTEIO,
#endif
#ifdef EDQUOT
EDQUOT,
#endif
#ifdef ENOMEDIUM
ENOMEDIUM,
#endif
#ifdef EMEDIUMTYPE
EMEDIUMTYPE,
#endif
0 };
char *constant_names[] = {
#ifdef PRIO_PROCESS
"PRIO_PROCESS",
#endif
#ifdef PRIO_PGRP
"PRIO_PGRP",
#endif
#ifdef PRIO_USER
"PRIO_USER",
#endif
#ifdef SIGHUP
"SIGHUP",
#endif
#ifdef SIGINT
"SIGINT",
#endif
#ifdef SIGQUIT
"SIGQUIT",
#endif
#ifdef SIGILL
"SIGILL",
#endif
#ifdef SIGTRAP
"SIGTRAP",
#endif
#ifdef SIGABRT
"SIGABRT",
#endif
#ifdef SIGBUS
"SIGBUS",
#endif
#ifdef SIGFPE
"SIGFPE",
#endif
#ifdef SIGKILL
"SIGKILL",
#endif
#ifdef SIGUSR1
"SIGUSR1",
#endif
#ifdef SIGSEGV
"SIGSEGV",
#endif
#ifdef SIGUSR2
"SIGUSR2",
#endif
#ifdef SIGPIPE
"SIGPIPE",
#endif
#ifdef SIGALRM
"SIGALRM",
#endif
#ifdef SIGTERM
"SIGTERM",
#endif
#ifdef SIGCHLD
"SIGCHLD",
#endif
#ifdef SIGCONT
"SIGCONT",
#endif
#ifdef SIGSTOP
"SIGSTOP",
#endif
#ifdef SIGTSTP
"SIGTSTP",
#endif
#ifdef SIGTTIN
"SIGTTIN",
#endif
#ifdef SIGTTOU
"SIGTTOU",
#endif
#ifdef SIGURG
"SIGURG",
#endif
#ifdef SIGXCPU
"SIGXCPU",
#endif
#ifdef SIGXFSZ
"SIGXFSZ",
#endif
#ifdef SIGVTALRM
"SIGVTALRM",
#endif
#ifdef SIGPROF
"SIGPROF",
#endif
#ifdef SIGWINCH
"SIGWINCH",
#endif
#ifdef SIGIO
"SIGIO",
#endif
#ifdef SIGSTKFLT
"SIGSTKFLT",
#endif
#ifdef RLIMIT_CPU
"RLIMIT_CPU",
#endif
#ifdef RLIMIT_DATA
"RLIMIT_DATA",
#endif
#ifdef RLIMIT_FSIZE
"RLIMIT_FSIZE",
#endif
#ifdef RLIMIT_MEMLOCK
"RLIMIT_MEMLOCK",
#endif
#ifdef RLIMIT_NOFILE
"RLIMIT_NOFILE",
#endif
#ifdef RLIMIT_NPROC
"RLIMIT_NPROC",
#endif
#ifdef RLIMIT_RSS
"RLIMIT_RSS",
#endif
#ifdef RLIMIT_STACK
"RLIMIT_STACK",
#endif
#ifdef RLIM_INFINITY
"RLIM_INFINITY",
#endif
#ifdef RLIMIT_LOCKS
"RLIMIT_LOCKS",
#endif
#ifdef EPERM
"EPERM",
#endif
#ifdef ENOENT
"ENOENT",
#endif
#ifdef ESRCH
"ESRCH",
#endif
#ifdef EINTR
"EINTR",
#endif
#ifdef EIO
"EIO",
#endif
#ifdef ENXIO
"ENXIO",
#endif
#ifdef E2BIG
"E2BIG",
#endif
#ifdef ENOEXEC
"ENOEXEC",
#endif
#ifdef EBADF
"EBADF",
#endif
#ifdef ECHILD
"ECHILD",
#endif
#ifdef EAGAIN
"EAGAIN",
#endif
#ifdef ENOMEM
"ENOMEM",
#endif
#ifdef EACCES
"EACCES",
#endif
#ifdef EFAULT
"EFAULT",
#endif
#ifdef ENOTBLK
"ENOTBLK",
#endif
#ifdef EBUSY
"EBUSY",
#endif
#ifdef EEXIST
"EEXIST",
#endif
#ifdef EXDEV
"EXDEV",
#endif
#ifdef ENODEV
"ENODEV",
#endif
#ifdef ENOTDIR
"ENOTDIR",
#endif
#ifdef EISDIR
"EISDIR",
#endif
#ifdef EINVAL
"EINVAL",
#endif
#ifdef ENFILE
"ENFILE",
#endif
#ifdef EMFILE
"EMFILE",
#endif
#ifdef ENOTTY
"ENOTTY",
#endif
#ifdef ETXTBSY
"ETXTBSY",
#endif
#ifdef EFBIG
"EFBIG",
#endif
#ifdef ENOSPC
"ENOSPC",
#endif
#ifdef ESPIPE
"ESPIPE",
#endif
#ifdef EROFS
"EROFS",
#endif
#ifdef EMLINK
"EMLINK",
#endif
#ifdef EPIPE
"EPIPE",
#endif
#ifdef EDOM
"EDOM",
#endif
#ifdef ERANGE
"ERANGE",
#endif
#ifdef EDEADLK
"EDEADLK",
#endif
#ifdef ENAMETOOLONG
"ENAMETOOLONG",
#endif
#ifdef ENOLCK
"ENOLCK",
#endif
#ifdef ENOSYS
"ENOSYS",
#endif
#ifdef ENOTEMPTY
"ENOTEMPTY",
#endif
#ifdef ELOOP
"ELOOP",
#endif
#ifdef EWOULDBLOCK
"EWOULDBLOCK",
#endif
#ifdef ENOMSG
"ENOMSG",
#endif
#ifdef EIDRM
"EIDRM",
#endif
#ifdef ECHRNG
"ECHRNG",
#endif
#ifdef EL2NSYNC
"EL2NSYNC",
#endif
#ifdef EL3HLT
"EL3HLT",
#endif
#ifdef EL3RST
"EL3RST",
#endif
#ifdef ELNRNG
"ELNRNG",
#endif
#ifdef EUNATCH
"EUNATCH",
#endif
#ifdef ENOCSI
"ENOCSI",
#endif
#ifdef EL2HLT
"EL2HLT",
#endif
#ifdef EBADE
"EBADE",
#endif
#ifdef EBADR
"EBADR",
#endif
#ifdef EXFULL
"EXFULL",
#endif
#ifdef ENOANO
"ENOANO",
#endif
#ifdef EBADRQC
"EBADRQC",
#endif
#ifdef EBADSLT
"EBADSLT",
#endif
#ifdef EBFONT
"EBFONT",
#endif
#ifdef ENOSTR
"ENOSTR",
#endif
#ifdef ENODATA
"ENODATA",
#endif
#ifdef ETIME
"ETIME",
#endif
#ifdef ENOSR
"ENOSR",
#endif
#ifdef ENONET
"ENONET",
#endif
#ifdef ENOPKG
"ENOPKG",
#endif
#ifdef EREMOTE
"EREMOTE",
#endif
#ifdef ENOLINK
"ENOLINK",
#endif
#ifdef EADV
"EADV",
#endif
#ifdef ESRMNT
"ESRMNT",
#endif
#ifdef ECOMM
"ECOMM",
#endif
#ifdef EPROTO
"EPROTO",
#endif
#ifdef EMULTIHOP
"EMULTIHOP",
#endif
#ifdef EDOTDOT
"EDOTDOT",
#endif
#ifdef EBADMSG
"EBADMSG",
#endif
#ifdef EOVERFLOW
"EOVERFLOW",
#endif
#ifdef ENOTUNIQ
"ENOTUNIQ",
#endif
#ifdef EBADFD
"EBADFD",
#endif
#ifdef EREMCHG
"EREMCHG",
#endif
#ifdef ELIBACC
"ELIBACC",
#endif
#ifdef ELIBBAD
"ELIBBAD",
#endif
#ifdef ELIBSCN
"ELIBSCN",
#endif
#ifdef ELIBMAX
"ELIBMAX",
#endif
#ifdef ELIBEXEC
"ELIBEXEC",
#endif
#ifdef EILSEQ
"EILSEQ",
#endif
#ifdef ERESTART
"ERESTART",
#endif
#ifdef ESTRPIPE
"ESTRPIPE",
#endif
#ifdef EUSERS
"EUSERS",
#endif
#ifdef ENOTSOCK
"ENOTSOCK",
#endif
#ifdef EDESTADDRREQ
"EDESTADDRREQ",
#endif
#ifdef EMSGSIZE
"EMSGSIZE",
#endif
#ifdef EPROTOTYPE
"EPROTOTYPE",
#endif
#ifdef ENOPROTOOPT
"ENOPROTOOPT",
#endif
#ifdef EPROTONOSUPPORT
"EPROTONOSUPPORT",
#endif
#ifdef ESOCKTNOSUPPORT
"ESOCKTNOSUPPORT",
#endif
#ifdef EOPNOTSUPP
"EOPNOTSUPP",
#endif
#ifdef EPFNOSUPPORT
"EPFNOSUPPORT",
#endif
#ifdef EAFNOSUPPORT
"EAFNOSUPPORT",
#endif
#ifdef EADDRINUSE
"EADDRINUSE",
#endif
#ifdef EADDRNOTAVAIL
"EADDRNOTAVAIL",
#endif
#ifdef ENETDOWN
"ENETDOWN",
#endif
#ifdef ENETUNREACH
"ENETUNREACH",
#endif
#ifdef ENETRESET
"ENETRESET",
#endif
#ifdef ECONNABORTED
"ECONNABORTED",
#endif
#ifdef ECONNRESET
"ECONNRESET",
#endif
#ifdef ENOBUFS
"ENOBUFS",
#endif
#ifdef EISCONN
"EISCONN",
#endif
#ifdef ENOTCONN
"ENOTCONN",
#endif
#ifdef ESHUTDOWN
"ESHUTDOWN",
#endif
#ifdef ETOOMANYREFS
"ETOOMANYREFS",
#endif
#ifdef ETIMEDOUT
"ETIMEDOUT",
#endif
#ifdef ECONNREFUSED
"ECONNREFUSED",
#endif
#ifdef EHOSTDOWN
"EHOSTDOWN",
#endif
#ifdef EHOSTUNREACH
"EHOSTUNREACH",
#endif
#ifdef EALREADY
"EALREADY",
#endif
#ifdef EINPROGRESS
"EINPROGRESS",
#endif
#ifdef ESTALE
"ESTALE",
#endif
#ifdef EUCLEAN
"EUCLEAN",
#endif
#ifdef ENOTNAM
"ENOTNAM",
#endif
#ifdef ENAVAIL
"ENAVAIL",
#endif
#ifdef EISNAM
"EISNAM",
#endif
#ifdef EREMOTEIO
"EREMOTEIO",
#endif
#ifdef EDQUOT
"EDQUOT",
#endif
#ifdef ENOMEDIUM
"ENOMEDIUM",
#endif
#ifdef EMEDIUMTYPE
"EMEDIUMTYPE",
#endif
"" };
