#!/bin/sh
echo /\* This file was autogenerated by consts.sh from consts.txt \*/
echo long constant_values[] = {
for i in `cat $1`
do
  echo \#ifdef $i
  echo $i,
  echo \#endif
done
echo 0 }\;
echo char *constant_names[] = {
for i in `cat $1`
do
  echo \#ifdef $i
  echo \"$i\",
  echo \#endif
done
echo \"\" }\;
