#!/bin/sh

echo ">>>>>>>>>>>>>>>>>>>>> BUILDING FERITE PARSER"
rm -f ferite_parser.output
bison -v -d -p fep -b ferite_parser ferite_parser.y
mv ferite_parser.tab.c ferite_parser.c
mv ferite_parser.tab.h ../include/ferite/fparser.h
