/* numbers.fe (C) 20010114 Pete Vassoff <pfv@grex.org>
 *  Test assorted additions and changes to parser & scanner..
 */
uses "console";

number foz = 1;
final number binary = 0b00110000, octal = 0060, zero = 0;
final number decimal = 48, hex = 0x30, nzero = !0;

Console.println("Logical Constants:\n"
                +"\t(!zero=$nzero) true=" +true +"\n"
                +"\t( zero=$zero) false=" +false +"\n" );

Console.println( "If all is well they should all output 0 [zero]" );
Console.println( "Escapes:\n"
                 +"\t\\0060=\t\t'\0060'\n"
                 +"\t\\x30=\t\t'\x30'\n"
                 +"\t\\b00110000=\t'\b00110000'\n"
                 +"\t\\d48=\t\t'\d48'\n" );

Console.println( "Other codes: \0 (\a) \b \c \d \x\n" );
/*backspace still works, too! */

Console.println( "If all is well they should all output 48 [forty eight]" );
Console.println("Numbers:\n"
                +"\t0060=\t\t$octal\n"
                +"\t0x30=\t\t$hex\n"
                +"\t0b00110000=\t$binary\n"
                +"\t48=\t\t$decimal" );

// testing final
//
Console.println( "\nThis should now fail with an error about variable assignment to a final variable!\n" );
decimal = 10;
