uses "console", "thread", "sys";

class MyThread extends Thread
{
   function run()
   {
       1 + "Hello";
   }
}

object t1 = new MyThread();
number counter = 0;

t1.setPassExceptions( true );
t1.start();

while(true)
{
    counter++;
    Sys.usleep( 1000000 );
    Console.println( "Main Loop [$counter seconds passed]" );
    if( counter == 5 )
    {
        Console.println( "Stopping Script" );
        break;
    }
}

